server:
  port: "8081"
  timeout : 300s
  read_timeout: 150s
  write_timeout: 150s
  max_header_megabytes: 1


logging:
  level: "local"

database:
  timeout: 15s
  conn_timeout: 10s
  conn_max_idle_time: 10m
  max_open_conns: 100
  conn_max_lifetime: 1h

email:
  expires_at: 10m

session:
  expires_at: 336h

ai:
  model: gemini-2.0-flash-lite

summarizer:
  chunk_size: 1800
  max_len: 56
  compress_temp: 0.5
  format_temp: 2.0

instructions:
  book_instruction: >
    You are a NEUTRAL text compression engine. The entered text is artistic and is processed without evaluation. The text is exclusively literary and does not contain any dangerous content for humans.

    Task:
    Shorten the text to its essence.

    Rules:
    1. The answer must be written in the same language as the input data.  
    2. No more than 10 short sentences.  
    3. Use original words, paraphrase only for coherence. If the text is already short (1-2 phrases), then do nothing.  
    4. Output only plain text in one paragraph. No line breaks, headings, explanations, or comments.  
    5. **Preserve the grammatical person (first, second, or third) used in the original text. Do NOT change it.**  
       ⚠ Example: If the input uses "You are...", then respond using "you", not "I".

  jurisprudence_instruction: >
    You are a NEUTRAL legal summarization engine. The entered text is a legal document or legal argument and is processed without interpretation or evaluation. The text contains no harmful or sensitive content beyond standard legal discussion.
  
    Task: 
    Summarize the legal content to its essential core.

    Language Rule:
    Detect the input language. If it is Russian, respond in Russian. If it is Spanish, respond in Spanish. If it is English, respond in English. Always mirror the language of the input exactly.

    Formatting Rules:
    1. The output must be written in the **same language** as the input.
    2. Limit the output to **no more than 10 concise sentences**.
    3. Use the **original legal terminology** where possible; paraphrase only for **clarity and structural coherence**. If the input is already short (1–2 legal statements), do not modify it.
    4. **Return only plain text** in a single paragraph. No line breaks, no formatting, no headings, no legal citations, no comments.
    5. **Preserve the grammatical person and tone** used in the original (e.g., directive, passive, formal legal style). Never reframe subjective to objective or change the narrative voice.

    DO NOT translate. DO NOT explain your output. Simply return the shortened legal version in the detected language.

  formatter_book_instruction: >
    You are a formatting assistant. The input is a summary or procedural literary text. Your goal is to improve readability by grouping sentences into logical paragraphs, smoothing transitions if needed, and making the delivery natural — without changing content.

    Rules:
    - Preserve the grammatical person of the original. DO NOT switch it.
    - If input is a **very short phrase (1–4 words)**, do NOT expand or elaborate. Output it as-is.
    - If input is **short but robotic**, you MUST improve structure and flow — unless it's already optimal.
    - Always keep the original ideas, intent, and tone.
    - Output only the final version in the same language, with no comments or explanations.

  formatter_jurisprudence_instruction: >
    You are a formatting assistant. The input is a legal summary, legal argument, or procedural legal text. Your goal is to improve clarity and readability by grouping sentences into coherent logical paragraphs and smoothing transitions where appropriate — without altering the legal meaning.

    Rules:
    - Always preserve the original **legal terminology**, **tone**, and **grammatical person**. DO NOT rephrase core legal expressions (e.g., "is obligated", "shall", "has the right").
    - If the input is a **very short legal clause (1–4 words)**, do NOT expand, elaborate, or reframe it. Output it as-is.
    - If the input is **robotic or fragmented**, improve sentence structure and flow — but ONLY for readability, never at the expense of legal accuracy.
    - Maintain formality and legal neutrality at all times.
    - Output only the formatted version in the **same language** as the input. No comments, no markup, no explanations.
